name: Build Binaries

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-linux-android
            android: true
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-ios
            ios: true

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install Android NDK (if needed)
        if: ${{ matrix.android }}
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d

      - name: Set up Android target (if needed)
        if: ${{ matrix.android }}
        run: |
          rustup target add aarch64-linux-android
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-android

      - name: Set up iOS target (if needed)
        if: ${{ matrix.ios }}
        run: rustup target add aarch64-apple-ios

      - name: Build
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-binary
          path: target/${{ matrix.target }}/release/clipboard-sync*
